version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-compose/snippets:/etc/nginx/snippets:ro
      - ./:/var/www/html
    depends_on:
      - php

  php:
    image: php:8.4-fpm
    volumes:
      - ./:/var/www/html
      - ./docker-compose/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
