services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker-compose/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-compose/snippets:/etc/nginx/snippets:ro
      - ./:/var/www/html
    depends_on:
      - api

  api:
    build:
      context: ./docker-compose/contexts/api
    volumes:
      - ./:/var/www/html
      - ./docker-compose/php.ini:/usr/local/etc/php/php.ini

  queue-worker:
    build:
      context: ./docker-compose/contexts/queue-worker
    restart: always
    command: php artisan queue:work
    volumes:
      - ./:/var/www/html/
    depends_on:
      - api

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: btc_tracker
      MYSQL_USER: tracker_user
      MYSQL_PASSWORD: btc_tr@k1ng_1sFuN!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-compose/contexts/mysql/create_test_database.sql:/docker-entrypoint-initdb.d/create_test_database.sql

volumes:
  mysql_data:
